name: Discloud Deploy Action

on:
  release:
    types: [created] # On release created
  workflow_dispatch: # Manual running

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Required to use the file system
      - uses: discloud/deploy-action@v1
        with:
          token: ${{ secrets.DISCLOUD_TOKEN }}
          # app_id: "ID"
          # team: true
